spring:
  application:
    name: customer-service

  profile:
    dev

  datasource:
    url: jdbc:postgresql://localhost:5432/openfeign_practise_db
    username: postgres
    password: tech
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
